INSERT INTO FRWK_CONFIG(CLAVE,VALOR,ID_APP,IS_FRWK,ID)  VALUES('NUMERO_DIAS_A_MOSTRAR', '8', 'respadel', 'S', 'ID');
INSERT INTO FRWK_CONFIG(CLAVE,VALOR,ID_APP,IS_FRWK,ID)  VALUES('NUMERO_MAXIMO_RESERVAS', '2', 'respadel', 'S', 'ID');
INSERT INTO FRWK_CONFIG(CLAVE,VALOR,ID_APP,IS_FRWK,ID)  VALUES('ELEMENTOS_PASO_PAGINACION', '10', 'respadel', 'S', 'ID');
INSERT INTO FRWK_CONFIG(CLAVE,VALOR,ID_APP,IS_FRWK,ID)  VALUES('USUARIOS_AUTORIZADOS', 'admin,user,U*,E*', 'respadel', 'S', 'ID');
