CREATE TABLE FRWK_CONFIG
(
  CLAVE    VARCHAR(128),
  VALOR    VARCHAR(1024),
  ID_APP   VARCHAR(16),
  IS_FRWK  VARCHAR(1),
  ID       VARCHAR(128)
);

CREATE TABLE FRWK_GEST_ERRORES
(
  VALOR   VARCHAR(4000),
  ID_APP  VARCHAR(16)
);

CREATE TABLE FRWK_LOGGING
(
  VALOR   VARCHAR(4000),
  ID_APP  VARCHAR(16)
);

CREATE TABLE FRWK_AUDIT_USU
(
  USUARIO      VARCHAR(64),
  ID_APP       VARCHAR(16),
  SINCRONO     CHAR(1),
  OBLIGATORIO  CHAR(1)
);

CREATE TABLE FRWK_AUDIT_SRV
(
  COD_SERVICIO      VARCHAR(254)          NOT NULL,
  IND_ACTIVO        VARCHAR(1),
  TIPO_SERVICIO     VARCHAR(1),
  ID_APP            VARCHAR(16),
  VAL_NOM_SALIDA    VARCHAR(254),
  IND_OBLIGATORIO   VARCHAR(1),
  VAL_NOM_SERVICIO  VARCHAR(254)
)

CREATE TABLE FRWK_AUDIT_EL_JAVA
(
  COD_SERVICIO    VARCHAR(254)            NOT NULL,
  COD_EL_JAVA     VARCHAR(32)             NOT NULL,
  IND_ACTIVO      VARCHAR(1),
  IND_ENTRADA     VARCHAR(1),
  NUM_PARAMETRO   INTEGER,
  VAL_XPATH       VARCHAR(254),
  VAL_NOM_SALIDA  VARCHAR(32)
);

CREATE TABLE FRWK_AUDIT_REG
(
  COD_REGISTRO   VARCHAR(20)              NOT NULL,
  FEC_HORA       TIMESTAMP(6),
  COD_USUARIO    VARCHAR(16),
  COD_SERVICIO   VARCHAR(220),
  ID_PETICION    VARCHAR(32),
  VAL_TIEMPO     INTEGER,
  VAL_EXCEPCION  VARCHAR(256),
  ID_APP         VARCHAR(16)
);

CREATE TABLE FRWK_AUDIT_CAMPO
(
  COD_REGISTRO  VARCHAR(20)               NOT NULL,
  NOM_CAMPO     VARCHAR(32)               NOT NULL,
  VAL_CAMPO     VARCHAR(32)
);

CREATE TABLE FRWK_LOG
(
  USUARIO     VARCHAR(100),
  TSTAM       TIMESTAMP(6),
  ID_APP      VARCHAR(12)                 NOT NULL,
  SERVIDOR    VARCHAR(1000)               NOT NULL,
  THREAD      VARCHAR(200),
  OPERACION   VARCHAR(200),
  CLASE       VARCHAR(1000)               NOT NULL,
  NIVEL       VARCHAR(100),
  MENSAJE     VARCHAR(2000),
  STACKTRACE  VARCHAR(2000),
  IDPETICION  VARCHAR(100)
)