CREATE SEQUENCE  "ID_DIA_FESTIVO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ID_INSCRIPCION_MEAPUNTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "ID_MEAPUNTO_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE;
CREATE SEQUENCE  "RESERVA_SEQ"  MINVALUE 1 MAXVALUE 999999999999999999999999999 INCREMENT BY 1 START WITH 121 CACHE 20 NOORDER  NOCYCLE;

CREATE TABLE "ACTIVIDAD" 
   (	"ID_ACTIVIDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(80 BYTE)
   );

CREATE TABLE "ADMIN" 
   (	"ID_ADMIN" VARCHAR2(80 BYTE)
   );

CREATE TABLE "CENTRO" 
   (	"ID_CENTRO" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(80 BYTE)
   );

CREATE TABLE "DIA_FESTIVO" 
   (	"ID_DIA_FESTIVO" NUMBER(*,0), 
	"DIA" DATE, 
	"FK_CENTRO" NUMBER(*,0)
   );

CREATE TABLE "FRANJA" 
   (	"ID_FRANJA" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(80 BYTE), 
	"FECHA_INICIO_VALIDEZ" TIMESTAMP (6), 
	"FECHA_FIN_VALIDEZ" TIMESTAMP (6), 
	"FRANJA_FESTIVOS" NUMBER(*,0)
   );

CREATE TABLE "FRANJA_DIA" 
   (	"ID_FRANJA_DIA" NUMBER(*,0), 
	"FK_FRANJA" NUMBER(*,0), 
	"HORA_INICIO" TIMESTAMP (6), 
	"HORA_FIN" TIMESTAMP (6)
   );

CREATE TABLE "INSCRIPCION_MEAPUNTO" 
   (	"ID_INSCRIPCION_MEAPUNTO" NUMBER(*,0), 
	"FK_MEAPUNTO" NUMBER(*,0), 
	"USUARIO" VARCHAR2(80 BYTE), 
	"EMAIL_USUARIO" VARCHAR2(500 BYTE)
   );
/

CREATE TABLE "INSTALACION" 
   (	"ID_INSTALACION" NUMBER(*,0), 
	"FK_CENTRO" NUMBER(*,0), 
	"FK_ACTIVIDAD" NUMBER(*,0), 
	"NOMBRE" VARCHAR2(80 BYTE)
   );

CREATE TABLE "INSTALACION_FRANJA" 
   (	"ID_INSTALACION_FRANJA" NUMBER(*,0), 
	"FK_INSTALACION" NUMBER(*,0), 
	"FK_FRANJA" NUMBER(*,0)
   );

CREATE TABLE "MEAPUNTO" 
   (	"ID_MEAPUNTO" NUMBER(*,0), 
	"FK_RESERVA" NUMBER(*,0), 
	"NIVEL_MINIMO" NUMBER(3,2), 
	"NIVEL_MAXIMO" NUMBER(3,2), 
	"NOTAS" VARCHAR2(500 BYTE), 
	"DIA_LIMITE" DATE, 
	"HORA_LIMITE" TIMESTAMP (6), 
	"INSCRITOS" NUMBER(*,0), 
	"ESTADO" VARCHAR2(1 BYTE)
   );

CREATE TABLE "RESERVA" 
   (	"ID_RESERVA" NUMBER(*,0), 
	"FK_FRANJA_DIA" NUMBER(*,0), 
	"FK_INSTALACION" NUMBER(*,0), 
	"DIA" DATE, 
	"FEC_HORA" TIMESTAMP (6), 
	"USUARIO" VARCHAR2(80 BYTE), 
	"NOMBRE_ORIGINAL" VARCHAR2(80 BYTE), 
	"ESTADO" VARCHAR2(1 BYTE)
   );



CREATE UNIQUE INDEX "PK_INSCRIPCION_MEAPUNTO" ON "INSCRIPCION_MEAPUNTO" ("ID_INSCRIPCION_MEAPUNTO");
CREATE UNIQUE INDEX "PK_CENTRO" ON "CENTRO" ("ID_CENTRO");
CREATE UNIQUE INDEX "PK_INSTALACION" ON "INSTALACION" ("ID_INSTALACION");
CREATE UNIQUE INDEX "PK_FRANJA_DIA" ON "FRANJA_DIA" ("ID_FRANJA_DIA");
CREATE UNIQUE INDEX "PK_ADMIN" ON "ADMIN" ("ID_ADMIN");
CREATE UNIQUE INDEX "PK_DIA_FESTIVO" ON "DIA_FESTIVO" ("ID_DIA_FESTIVO");
CREATE UNIQUE INDEX "PK_RESERVA" ON "RESERVA" ("ID_RESERVA");
CREATE UNIQUE INDEX "PK_INSTALACION_FRANJA" ON "INSTALACION_FRANJA" ("ID_INSTALACION_FRANJA");
CREATE UNIQUE INDEX "PK_MEAPUNTO" ON "MEAPUNTO" ("ID_MEAPUNTO");
CREATE UNIQUE INDEX "PK_ACTIVIDAD" ON "ACTIVIDAD" ("ID_ACTIVIDAD");
CREATE UNIQUE INDEX "PK_FRANJA" ON "FRANJA" ("ID_FRANJA");
