CREATE TABLE "FRWK_CONFIG" 
 (	"CLAVE" VARCHAR2(128), 
      "VALOR" VARCHAR2(1024), 
      "ID_APP" VARCHAR2(16), 
      "IS_FRWK" VARCHAR2(1), 
      "ID" VARCHAR2(128)
 );

CREATE TABLE "FRWK_GEST_ERRORES" 
 (	"VALOR" VARCHAR2(4000), 
      "ID_APP" VARCHAR2(16)
 );

CREATE TABLE "FRWK_LOGGING" 
 (	"VALOR" VARCHAR2(4000), 
      "ID_APP" VARCHAR2(16)
 );

CREATE TABLE "FRWK_AUDIT_USU" 
 (	"USUARIO" VARCHAR2(64), 
      "ID_APP" VARCHAR2(16), 
      "SINCRONO" CHAR(1), 
      "OBLIGATORIO" CHAR(1)
 );

CREATE TABLE "FRWK_AUDIT_SRV" 
 (	"COD_SERVICIO" VARCHAR2(254), 
      "IND_ACTIVO" VARCHAR2(1), 
      "TIPO_SERVICIO" VARCHAR2(1), 
      "ID_APP" VARCHAR2(16), 
      "VAL_NOM_SALIDA" VARCHAR2(254), 
      "IND_OBLIGATORIO" VARCHAR2(1), 
      "VAL_NOM_SERVICIO" VARCHAR2(255)
 );


CREATE TABLE "FRWK_AUDIT_EL_JAVA" 
 (	"COD_SERVICIO" VARCHAR2(254), 
      "COD_EL_JAVA" VARCHAR2(32), 
      "IND_ACTIVO" VARCHAR2(1), 
      "IND_ENTRADA" VARCHAR2(1), 
      "NUM_PARAMETRO" NUMBER(*,0), 
      "VAL_XPATH" VARCHAR2(254), 
      "VAL_NOM_SALIDA" VARCHAR2(32)
 );


CREATE TABLE "FRWK_AUDIT_REG" 
 (	"COD_REGISTRO" VARCHAR2(20), 
      "FEC_HORA" TIMESTAMP (6), 
      "COD_USUARIO" VARCHAR2(16), 
      "COD_SERVICIO" VARCHAR2(220), 
      "ID_PETICION" VARCHAR2(32), 
      "VAL_TIEMPO" NUMBER(*,0), 
      "VAL_EXCEPCION" VARCHAR2(256), 
      "ID_APP" VARCHAR2(16)
 );

CREATE TABLE "FRWK_AUDIT_CAMPO" 
 (	"COD_REGISTRO" VARCHAR2(20), 
      "NOM_CAMPO" VARCHAR2(32), 
      "VAL_CAMPO" VARCHAR2(255), 
      "FEC_HORA" TIMESTAMP (6)
 );


CREATE TABLE "FRWK_LOG"
(
  USUARIO     VARCHAR2(100),
  TSTAM       TIMESTAMP(6),
  ID_APP      VARCHAR2(12),
  SERVIDOR    VARCHAR2(1000),
  THREAD      VARCHAR2(200),
  OPERACION   VARCHAR2(200),
  CLASE       VARCHAR2(1000),
  NIVEL       VARCHAR2(100),
  MENSAJE     VARCHAR2(2000),
  STACKTRACE  VARCHAR2(2000),
  IDPETICION  VARCHAR2(100)
);


